### ISSUE TITLE
Is this plugin open source?

### ISSUE THREAD

**Issue by cnelson** [swisscom/docs-appcloud-service-connector#1]
Hello,

Is the plugin this documentation refers to open source?  If so, could you point me at the codebase?

**Comment by AndiBrunner** [comment]
Hi cnelson,

No, right now the service connector is not open source. It has a lot of Swisscom specific code in it and currently there are no plans to make it open source. The service-connector consists of two parts: the cli plugin (client-side proxy) and the service-proxy on the (server-side). They are communicating over a web socket tunnel and all client tcp connections are multiplexed over this tunnel.

**Comment by cnelson** [comment]
Thanks for getting back to me!

A pity it's not open, I found these docs googling as we have a need for a similar tool and was hoping to not reinvent the wheel. c'est la vie.
